spring:
  application:
    name: config-prod
eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/
